### ISSUE TITLE
Dragon don't load core modules.

### ISSUE THREAD

**Issue by Hi6ime1** [Dragon-Userbot/Dragon-Userbot#101]
After replacing my changed core module python.py, dragon saying that "module does not exist"

**Comment by Hi6ime1** [comment]
![image](https://github.com/Dragon-Userbot/Dragon-Userbot/assets/95527166/0b02ed98-4b87-4c85-8c97-54f44a77e131)
Before replacing file
![image](https://github.com/Dragon-Userbot/Dragon-Userbot/assets/95527166/446dd5a0-7ab0-42a8-b856-438f54becc2e)
After replacing file

**Comment by Hi6ime1** [comment]
If anything, nothing has been added to the file except emojis

**Comment by fuccsoc** [comment]
Please, provide changed code to investigate the issue.

**Comment by fuccsoc** [comment]
Или используй русский язык вместо ломанного английского...

**Comment by fuccsoc** [comment]
Inactive
