### ISSUE TITLE
Having some issues with installation

### ISSUE THREAD

**Issue by plasticsummer** [Dragon-Userbot/Dragon-Userbot#59]
(venv)  mac@macs-MacBook-Pro  ~/Dragon-Userbot   master  echo Enter your db_url: && read uservar && python3 install.py $uservar
Enter your db_url:
mongodb+srv://vanilla(can't show the password)@cluster0.ikvnj.mongodb.net/Dragon_Userbot?retryWrites=true&w=majority
Traceback (most recent call last):
  File "install.py", line 22, in <module>
    from utils import config
  File "/Users/mac/Dragon-Userbot/utils/config.py", line 6, in <module>
    api_id = env.int("API_ID")
  File "/Users/mac/Dragon-Userbot/venv/lib/python3.8/site-packages/environs/__init__.py", line 116, in method
    raise EnvError('Environment variable "{}" not set'.format(proxied_key or parsed_key))
environs.EnvError: Environment variable "API_ID" not set
(venv)  ✘ mac@macs-MacBook-Pro  ~/Dragon-Userbot   master 

**Comment by iamnalinor** [comment]
Copy .env.dist to .env with the following command:

`cp .env.dist .env`

Then, fill environment file with:

- API_ID & API_HASH (optional, but recommended)
- If you want to use Sqlite: `DATABASE_TYPE=sqlite3` and `DATABASE_NAME=db.sqlite3`
- If you want to use **local** MongoDB: `DATABASE_TYPE=mongodb`, `DATABASE_NAME=Dragon_Userbot` and `DATABASE_URL=mongodb://localhost:27017`

If you don't know what to choose, select Sqlite.

---

If you have any other questions, please ask them in the support chats, without opening an issue on GitHub: https://t.me/Dragon_Userbot_chat_en (english), https://t.me/Dragon_Userbot_chat (russian).

**Comment by lkqas** [comment]
@iamnalinor Ок
