### ISSUE TITLE
Transfer dict object

### ISSUE THREAD

**Issue by fleef-me** [Dragon-Userbot/Dragon-Userbot#77]
- If the object is static and does not change, then why not move it to utils.py?

https://github.com/Dragon-Userbot/Dragon-Userbot/blob/cc24c9759bab3d288d6bd4a347e170936dbd8edc/modules/spam.py#L32

**Comment by iamnalinor** [comment]
1. This object required only by spam module. If every module will create their variables in misc.py file, there will be a lot of unnecessary variables. misc.py contain only those variables that needed by all modules.
2. This dict was removed in v3.2 branch, please check.

**Comment by fleef-me** [comment]
> 1. This object required only by spam module. If every module will create their variables in misc.py file, there will be a lot of unnecessary variables. misc.py contain only those variables that needed by all modules.
> 
>     2. This dict was removed in v3.2 branch, please check.

Nice
